local palate = {
	Normal = { fg = "#FFFAF0", bg = "#000000" },
	Debug = { link = "Normal" },
	Identifier = { link = "Normal" },
	Operator = { link = "Normal" },
	Boolean = { fg = "#FFFAF0" },
	Character = { fg = "#0074BD" },
	ColorColumn = { bg = "#808080" },
	Comment = { fg = "#808080" },
	Conditional = { fg = "#FFFAF0", italic = true },
	Exception = { link = "Conditional" },
	Constant = { fg = "#FFFAF0", bold = true },
	CurSearch = { fg = "#FFFAF0", bg = "#D99059" },
	Cursor = { bg = "#C61585" },
	Delimiter = { fg = "#FFFAF0" },
	DiagnosticError = { fg = "#DB143C" },
	DiagnosticFloatingError = { fg = "#DB143C", bg = "#252225" },
	DiagnosticFloatingHint = { fg = "#32CD32", bg = "#252225" },
	DiagnosticFloatingOk = { link = "DiagnosticFloatingHint" },
	DiagnosticFloatingInfo = { fg = "#0074BD", bg = "#252225" },
	DiagnosticFloatingWarn = { fg = "#FFD900", bg = "#252225" },
	DiagnosticHint = { fg = "#32CD32" },
	DiagnosticOk = { link = "DiagnosticHint" },
	DiagnosticInfo = { fg = "#0074BD" },
	DiagnosticSignError = { fg = "#DB143C" },
	DiagnosticSignHint = { fg = "#32CD32" },
	DiagnosticSignOk = { link = "DiagnosticSignHint" },
	DiagnosticSignInfo = { fg = "#0074BD" },
	DiagnosticSignWarn = { fg = "#FFD900" },
	DiagnosticUnderlineError = { sp = "#DB143C", undercurl = true },
	DiagnosticUnderlineHint = { undercurl = true },
	DiagnosticUnderlineOk = { link = "DiagnosticUnderlineHint" },
	DiagnosticUnderlineInfo = { sp = "#0074BD", undercurl = true },
	DiagnosticUnderlineWarn = { sp = "#FFD900", undercurl = true },
	DiagnosticVirtualTextError = { fg = "#DB143C" },
	DiagnosticVirtualTextHint = { fg = "#32CD32" },
	DiagnosticVirtualTextOk = { link = "DiagnosticVirtualTextHint" },
	DiagnosticVirtualTextInfo = { fg = "#0074BD" },
	DiagnosticVirtualTextWarn = { fg = "#FFD900" },
	DiagnosticWarn = { fg = "#FFD900" },
	DiffAdd = { fg = "#32CD32" },
	DiffDelete = { fg = "#DB143C" },
	Error = { fg = "#DB143C" },
	ErrorMsg = { fg = "#DB143C" },
	Float = { fg = "#FFFAF0" },
	FloatBorder = { fg = "#FFFAF0" },
	Function = { fg = "#FFFAF0" },
	GitSignsAdd = { fg = "#32CD32" },
	GitSignsChange = { fg = "#0074BD" },
	GitSignsDelete = { fg = "#DB143C" },
	Ignore = {},
	Include = { fg = "#FFFAF0" },
	Define = { link = "Include" },
	Keyword = { fg = "#FFFAF0", italic = true },
	Label = { fg = "#FFFAF0" },
	PreProc = { link = "Label" },
	LineNr = { fg = "#FFFAF0" },
	LineNrAbove = { fg = "#808080" },
	LineNrBelow = { fg = "#808080" },
	LspSignatureActiveParameter = { fg = "#FAFAFF", bg = "#808080" },
	Macro = { fg = "#FFFAF0" },
	MatchParen = { fg = "#C61585" },
	NormalFloat = { fg = "#FAFAFF", bg = "#252225" },
	Number = { fg = "#0074BD" },
	Pmenu = { fg = "#FAFAFF", bg = "#252225" },
	PmenuKind = { link = "Pmenu" },
	PmenuSbar = { fg = "#000000", bg = "#808080" },
	PmenuSel = { fg = "#000000", bg = "#FFFAF0" },
	PmenuKindSel = { link = "PmenuSel" },
	PmenuThumb = { fg = "#FAFAFF" },
	PreCondit = { fg = "#FFFAF0" },
	Repeat = { fg = "#FFFAF0", italic = true },
	Search = { fg = "#000000", bg = "#D99059" },
	Special = { fg = "#FFFAF0" },
	SpecialChar = { fg = "#D99059" },
	SpecialComment = { fg = "#32CD32" },
	Statement = { fg = "#FFFAF0" },
	StatusLine = { fg = "#000000", bg = "#FFFAF0" },
	StorageClass = { fg = "#FFFAF0" },
	String = { fg = "#32CD32" },
	Structure = { fg = "#FFFAF0" },
	Substitute = { fg = "#000000", bg = "#D99059" },
	Tag = { fg = "#FFFAF0" },
	Todo = { fg = "#000000", bg = "#FFD900" },
	Type = { fg = "#FFFAF0" },
	Typedef = { fg = "#FFFAF0" },
	Underlined = { underline = true },
	WarningMsg = { fg = "#FFD900" },
	["@diff.delta"] = { fg = "#0074BD", bg = "#000000" },
	["@diff.minus"] = { fg = "#DB143C", bg = "#000000" },
	["@diff.plus"] = { fg = "#32CD32", bg = "#000000" },
}

local M = {}
function M.setup()
	for name, val in pairs(palate) do
		vim.api.nvim_set_hl(0, name, val)
	end
end

return M
