local palate = {
	Normal = { fg = "#FFFAF0", bg = "#000000" },
	Debug = { link = "Normal" },
	Identifier = { link = "Normal" },
	Operator = { link = "Normal" },
	Boolean = { fg = "#FFFAF0" },
	Character = { fg = "#0074BD" },
	ColorColumn = { bg = "#808080" },
	Comment = { fg = "#808080" },
	Conditional = { fg = "#FFFAF0", italic = true },
	Exception = { link = "Conditional" },
	Constant = { fg = "#FFFAF0", bold = true },
	CurSearch = { fg = "#FFFAF0", bg = "#D99059" },
	Cursor = { bg = "#C61585" },
	Delimiter = { fg = "#FFFAF0" },
	DiagnosticError = { fg = "#DB143C" },
	DiagnosticFloatingError = { fg = "#DB143C", bg = "#252225" },
	DiagnosticFloatingHint = { fg = "#32CD32", bg = "#252225" },
	DiagnosticFloatingOk = { link = "DiagnosticFloatingHint" },
	DiagnosticFloatingInfo = { fg = "#0074BD", bg = "#252225" },
	DiagnosticFloatingWarn = { fg = "#FFD900", bg = "#252225" },
	DiagnosticHint = { fg = "#32CD32" },
	DiagnosticOk = { link = "DiagnosticHint" },
	DiagnosticInfo = { fg = "#0074BD" },
	DiagnosticSignError = { fg = "#DB143C" },
	DiagnosticSignHint = { fg = "#32CD32" },
	DiagnosticSignOk = { link = "DiagnosticSignHint" },
	DiagnosticSignInfo = { fg = "#0074BD" },
	DiagnosticSignWarn = { fg = "#FFD900" },
	DiagnosticUnderlineError = { sp = "#DB143C", undercurl = true },
	DiagnosticUnderlineHint = { undercurl = true },
	DiagnosticUnderlineOk = { link = "DiagnosticUnderlineHint" },
	DiagnosticUnderlineInfo = { sp = "#0074BD", undercurl = true },
	DiagnosticUnderlineWarn = { sp = "#FFD900", undercurl = true },
	DiagnosticVirtualTextError = { fg = "#DB143C" },
	DiagnosticVirtualTextHint = { fg = "#32CD32" },
	DiagnosticVirtualTextOk = { link = "DiagnosticVirtualTextHint" },
	DiagnosticVirtualTextInfo = { fg = "#0074BD" },
	DiagnosticVirtualTextWarn = { fg = "#FFD900" },
	DiagnosticWarn = { fg = "#FFD900" },
	DiffAdd = { fg = "#32CD32" },
	DiffDelete = { fg = "#DB143C" },
	Error = { fg = "#DB143C" },
	ErrorMsg = { fg = "#DB143C" },
	Float = { fg = "#FFFAF0" },
	FloatBorder = { fg = "#FFFAF0" },
	Function = { fg = "#FFFAF0" },
	GitSignsAdd = { fg = "#32CD32" },
	GitSignsChange = { fg = "#0074BD" },
	GitSignsDelete = { fg = "#DB143C" },
	Ignore = {},
	Include = { fg = "#FFFAF0" },
	Define = { link = "Include" },
	Keyword = { fg = "#FFFAF0", italic = true },
	Label = { fg = "#FFFAF0" },
	PreProc = { link = "Label" },
	LineNr = { fg = "#FFFAF0" },
	LineNrAbove = { fg = "#808080" },
	LineNrBelow = { fg = "#808080" },
	LspSignatureActiveParameter = { fg = "#FAFAFF", bg = "#808080" },
	Macro = { fg = "#FFFAF0" },
	MatchParen = { fg = "#C61585" },
	NormalFloat = { fg = "#FAFAFF", bg = "#252225" },
	Number = { fg = "#0074BD" },
	Pmenu = { fg = "#FAFAFF", bg = "#252225" },
	PmenuKind = { link = "Pmenu" },
	PmenuSbar = { fg = "#000000", bg = "#808080" },
	PmenuSel = { fg = "#000000", bg = "#FFFAF0" },
	PmenuKindSel = { link = "PmenuSel" },
	PmenuThumb = { fg = "#FAFAFF" },
	PreCondit = { fg = "#FFFAF0" },
	Repeat = { fg = "#FFFAF0", italic = true },
	Search = { fg = "#000000", bg = "#D99059" },
	Special = { fg = "#FFFAF0" },
	SpecialChar = { fg = "#D99059" },
	SpecialComment = { fg = "#32CD32" },
	Statement = { fg = "#FFFAF0" },
	StatusLine = { fg = "#000000", bg = "#FFFAF0" },
	StorageClass = { fg = "#FFFAF0" },
	String = { fg = "#32CD32" },
	Structure = { fg = "#FFFAF0" },
	Substitute = { fg = "#000000", bg = "#D99059" },
	Tag = { fg = "#FFFAF0" },
	Todo = { fg = "#000000", bg = "#FFD900" },
	Type = { fg = "#FFFAF0" },
	Typedef = { fg = "#FFFAF0" },
	Underlined = { underline = true },
	WarningMsg = { fg = "#FFD900" },
	["@boolean"] = { fg = "#FFFAF0" },
	["@character"] = { fg = "#FFFAF0" },
	["@character.special"] = { fg = "#D99059" },
	["@comment"] = { fg = "#808080" },
	["@conditional"] = { fg = "#FFFAF0" },
	["@constant"] = { fg = "#FFFAF0" },
	["@constant.builtin"] = { fg = "#FFFAF0" },
	["@constant.macro"] = { fg = "#FFFAF0" },
	["@constructor"] = { fg = "#FFFAF0" },
	["@debug"] = { fg = "#FFFAF0" },
	["@define"] = {},
	["@diff.delta"] = { fg = "#0074BD", bg = "#000000" },
	["@diff.minus"] = { fg = "#DB143C", bg = "#000000" },
	["@diff.plus"] = { fg = "#32CD32", bg = "#000000" },
	["@exception"] = { fg = "#FFFAF0" },
	["@field"] = { fg = "#FFFAF0" },
	["@float"] = { fg = "#0074BD" },
	["@function"] = { fg = "#FFFAF0" },
	["@function.builtin"] = { fg = "#FFFAF0" },
	["@function.macro"] = { fg = "#FFFAF0" },
	["@include"] = { fg = "#FFFAF0" },
	["@keyword"] = { fg = "#FFFAF0" },
	["@label"] = { fg = "#FFFAF0" },
	["@macro"] = { fg = "#DB143C" },
	["@method"] = { fg = "#FFFAF0" },
	["@namespace"] = { fg = "#FFFAF0" },
	["@number"] = { fg = "#0074BD" },
	["@operator"] = { fg = "#FFFAF0" },
	["@parameter"] = { fg = "#FFFAF0" },
	["@preproc"] = { fg = "#FFFAF0" },
	["@property"] = { fg = "#FFFAF0" },
	["@punctuation"] = { fg = "#C61585" },
	["@repeat"] = { fg = "#FFFAF0" },
	["@spell"] = { fg = "#808080" },
	["@storageclass"] = { fg = "#FFFAF0" },
	["@string"] = { fg = "#32CD32" },
	["@string.escape"] = { fg = "#D99059" },
	["@string.special"] = { fg = "#D99059" },
	["@structure"] = { fg = "#FFFAF0" },
	["@tag"] = { fg = "#FFFAF0" },
	["@text.literal"] = { fg = "#D99059" },
	["@text.reference"] = { fg = "#FFFAF0" },
	["@text.title"] = { fg = "#FFFAF0" },
	["@text.todo"] = { fg = "#808080", bg = "#0074BD" },
	["@text.underline"] = { fg = "#FFFAF0" },
	["@text.uri"] = { fg = "#FFFAF0" },
	["@type"] = { fg = "#FFFAF0" },
	["@type.definition"] = { fg = "#FFFAF0" },
	["@variable"] = { fg = "#FFFAF0" },
}

local M = {}
function M.setup()
	for name, val in pairs(palate) do
		vim.api.nvim_set_hl(0, name, val)
	end
end
return M
